### ISSUE TITLE
bug: the Title field on artwork with impact tag is 1px too high

### ISSUE THREAD

**Issue by ccerv1** [hypercerts-org/hypercerts#371]
### Which area(s) of Hypercerts are affected? (leave empty if unsure)

Frontend Dapp

### To Reproduce

Go to any url, toggle the impact end date "indefinite" field on and off. The title line will shift up every so slightly (by one pixel)

### Describe the Bug

The `min height` in the title element is off by 1px

### Expected Behavior

The height of the title should not move regardless of whether an impact tag is displayed or not

**Comment by ccerv1** [comment]
Update: it's off by 0.5 px 😞

**Comment by ccerv1** [comment]
@ryscheng I think I have fixed this in Hypercerts Core -- if I toggle the impact settings in preview mode, it looks perfectly aligned. However, the change doesn't appear to be showing up in Hypercerts Dapp. We can discuss briefly in standup.

**Comment by ryscheng** [comment]
This has been published, wanna check if its still an issue? CC @ccerv1

**Comment by ccerv1** [comment]
Yes. Thank you 🙏
